import fs from 'fs/promises';
import path from 'path';
import chalk from 'chalk';
import inquirer from 'inquirer';
import { loadTemplates } from '../utils/template-loader.js';

interface InitOptions {
  output: string;
  interactive: boolean;
}

export async function initCommand(options: InitOptions) {
  console.log(chalk.blue.bold('\n🚀 Initialize GitHub Copilot Instructions\n'));

  try {
    const templates = await loadTemplates();

    if (templates.length === 0) {
      console.log(chalk.yellow('No templates found.'));
      return;
    }

    let selectedTemplates: string[];

    if (options.interactive) {
      // Interactive mode
      const answers = await inquirer.prompt([
        {
          type: 'checkbox',
          name: 'templates',
          message: 'Select templates to combine:',
          choices: templates.map((t) => ({
            name: `${t.frontmatter?.title || t.filename} (${t.id})`,
            value: t.id,
            short: t.id,
          })),
          validate: (input) => {
            if (input.length === 0) {
              return 'Please select at least one template';
            }
            return true;
          },
        },
      ]);

      selectedTemplates = answers.templates;
    } else {
      // Non-interactive mode - use all templates
      console.log(chalk.yellow('Non-interactive mode not fully implemented yet.'));
      console.log(chalk.gray('Run without --no-interactive flag for template selection.'));
      return;
    }

    // Load selected templates
    const selected = templates.filter((t) => selectedTemplates.includes(t.id));

    // Combine templates
    const combined = combineTemplates(selected);

    // Ensure output directory exists
    const outputDir = path.dirname(options.output);
    await fs.mkdir(outputDir, { recursive: true });

    // Write output
    await fs.writeFile(options.output, combined, 'utf-8');

    console.log(chalk.green(`\n✅ Created: ${options.output}`));
    console.log(chalk.gray(`\nSelected templates: ${selectedTemplates.join(', ')}`));
    console.log(
      chalk.blue('\nNext steps:')
    );
    console.log(chalk.gray('  1. Review and customize the generated instructions'));
    console.log(chalk.gray('  2. Commit the file to your repository'));
    console.log(chalk.gray('  3. Start using GitHub Copilot with your custom instructions!\n'));
  } catch (error) {
    console.error(chalk.red('Error during initialization:'), error);
    process.exit(1);
  }
}

/**
 * Combine multiple templates into a single instruction file
 */
function combineTemplates(templates: any[]): string {
  let combined = '# GitHub Copilot Instructions\n\n';
  combined += '> **Note**: This file was generated by combining multiple templates.\n';
  combined += '> Customize it to fit your specific project needs.\n\n';
  combined += `> **Templates used**: ${templates.map((t) => t.id).join(', ')}\n\n`;
  combined += '---\n\n';

  for (const template of templates) {
    // Remove frontmatter from template content
    const contentWithoutFrontmatter = template.content.replace(/^---\s*\n[\s\S]*?\n---\s*\n/, '');

    // Remove the main title if it exists
    const contentWithoutTitle = contentWithoutFrontmatter.replace(/^#\s+[^\n]+\n+/, '');

    combined += contentWithoutTitle;
    combined += '\n\n---\n\n';
  }

  return combined;
}
